### ISSUE TITLE
Android: Keybord disappears when using context (cut/copy/...) menu

### ISSUE THREAD

**Issue by hanspagel** [heyscrumpy/tiptap#1]
When I use the Android context menu the keyboard disappears.

I would expect the keyboard won't disappear.

Screenrecording
![ezgif-4-16d5a65610](https://user-images.githubusercontent.com/1577992/44633020-4baa5a00-a985-11e8-8dbb-f432319051ba.gif)

**Comment by philippkuehn** [comment]
This seems to be an issue with Prosemirror. [https://github.com/ProseMirror/prosemirror/issues/794](https://github.com/ProseMirror/prosemirror/issues/794)
