### ISSUE TITLE
Syntax highlighting for code blocks

### ISSUE THREAD

**Issue by philippkuehn** [heyscrumpy/tiptap#10]
It would be nice to implement highlight.js or prism.js (or something else?) for syntax highlighting. Maybe this is possible through prosemirror decorations?

**Comment by philippkuehn** [comment]
I've already made progress. But I still have to implement some kind of caching.

![highlighting](https://user-images.githubusercontent.com/2500670/44956358-eee9fa80-aec2-11e8-8c60-e45431ad14e7.gif)

**Comment by bryantobing12** [comment]
is this already supported?
