### ISSUE TITLE
Insert a mention on button click

### ISSUE THREAD

**Issue by ilicmarko** [heyscrumpy/tiptap#100]
I am starting to use tiptap and I am liking it, but there is a **lack of documentation**. I would like to add a insert mention button can't find a proper way to do it.

You would have your usual mention for example `['author', 'me', 'mod']` and then you type `@aut` it would suggest `@author` but I would like to add buttons to the toolbar `Add Author tag`, `Add Me tag`... but to do this I need the `range` and `command`. How can I extract these?

This is the method I would add:

```
addFirstName() {
  this.insertMention({
    range: this.suggestionRange,
    attrs: {
      id: 1,
      label: '@author',
    },
  })
  this.editor.focus()
}
```
---

I am looking at Prosemirror examples and found the one with [dinos](https://prosemirror.net/examples/dino/). This is something similar to what I am trying to achieve.

My idea is when you click the button just add a `<span class="mention" data-mention-id="1" contenteditable="false">@autho</span>` at the current position and let the editor do the rest.

Unfortunately I lack documentation to implement this in tip tap 😢 Help is much needed.

I also think this can be added to examples as how to insert custom blocks (even like `<hr>`).

_I tried looking at tip tap example already._

Thank you in advance and keep up the great work.

**Comment by ilicmarko** [comment]
Here is my attempt but still not working 😭 

This is my custom node:

```javascript
import { Node } from 'tiptap'
import { replaceText } from 'tiptap-commands'

export default class TokenNode extends Node {

  get name() {
    return 'token'
  }

  get schema() {
    return {
      attrs: {
        id: {},
        label: {},
      },
      group: 'inline',
      inline: true,
      selectable: false,
      atom: true,
      toDOM: node => [
        'span',
        {
          class: 'mention',
          'data-mention-id': node.attrs.id,
        },
        `${node.attrs.label}`,
      ],
      parseDOM: [
        {
          tag: 'span[data-mention-id]',
          getAttrs: dom => {
            const id = dom.getAttribute('data-mention-id')
            const label = dom.innerText
            return { id, label }
          },
        },
      ],
    }
  }

  /*
  command: ({ range, attrs }) => {
    command({
      range,
      attrs,
      schema: view.state.schema,
    })(view.state, view.dispatch, view)

    if (appendText) {
      insertText(appendText)(view.state, view.dispatch, view)
    }
  }
   */

  commands({ range, attrs, schema }) {
    return () => replaceText(range, schema.nodes.mention, attrs)
  }
}
```

Here is my menu button:

```vue
<button class="menubar__variable" @click="commands.token({id: 1, label: 'author'})" >
  <Icon name="variable"/> Insert Variable
</button>
```

With this setup I get this error: 
```
Uncaught TypeError: Cannot read property 'from' of undefined
```

I get that the error is in the `commands` method and for some reason I can't insert the node at that place.

**Comment by philippkuehn** [comment]
Hey @ilicmarko, this is a good feature request. It's fixed in the latest version! 👍 I've also added such a button to the [example page](https://tiptap.scrumpy.io/suggestions).

![nov-22-2018 23-02-06](https://user-images.githubusercontent.com/2500670/48922989-e0502580-eeaa-11e8-9df5-a049a9673b9a.gif)

**Comment by sumitKumar1406** [comment]
@philippkuehn  i want to open custom menu and i am not getting the cursor position of @ inside the editor content.
