### ISSUE TITLE
Setting the selection programmatically

### ISSUE THREAD

**Issue by panayotisk** [heyscrumpy/tiptap#104]
Is there a way to set the selection programmatically? Looking at the Editor.js interface I did not spot something related to setting the selection. I need to be able to set the caret position on a double click event (not the default single click). Would I have to resort to the underlying ProseMirror?

Thank you!

**Comment by philippkuehn** [comment]
Hey,

working with selection could definitely a bit easier with prosemirror 😅
A few days ago I've changed how links works. So if you click on a link, the full link is selected so the bubble menu gets triggered and you could edit or delete your link. this looks something like that:

![nov-22-2018 22-26-16](https://user-images.githubusercontent.com/2500670/48922323-2c4c9b80-eea6-11e8-8ed1-1f3cd830a4d9.gif)

I've added a prosemirror plugin for doing this:

```js
import { Mark, Plugin, TextSelection } from 'tiptap'
import { getMarkRange } from 'tiptap-utils'

export default class Link extends Mark {

  // ...

  get plugins() {
    return [
      new Plugin({
        props: {
          handleClick(view, pos) {
            const { schema, doc, tr } = view.state
            const range = getMarkRange(doc.resolve(pos), schema.marks.link)

            if (!range) {
              return
            }

            const $start = doc.resolve(range.from)
            const $end = doc.resolve(range.to)
            const transaction = tr.setSelection(new TextSelection($start, $end))

            view.dispatch(transaction)
          },
        },
      }),
    ]
  }

}
```

Maybe that helps you a bit. Instead of `handleClick` there is also a `handleDoubleClick` event ([docs](https://prosemirror.net/docs/ref/#view.EditorProps)).

**Comment by panayotisk** [comment]
Yes this seems quite relevant to what I am trying to do. When I manage to make it work correctly I shall post my code here.

**Comment by philippkuehn** [comment]
There is method now.

```js
editor.setSelection(from, to)
editor.focus()
```

**Comment by usb248** [comment]
> 
> 
> Hey,
> 
> working with selection could definitely a bit easier with prosemirror 😅
> A few days ago I've changed how links works. So if you click on a link, the full link is selected so the bubble menu gets triggered and you could edit or delete your link. this looks something like that:
> 
> ![nov-22-2018 22-26-16](https://user-images.githubusercontent.com/2500670/48922323-2c4c9b80-eea6-11e8-8ed1-1f3cd830a4d9.gif)
> 
> I've added a prosemirror plugin for doing this:
> 
> ```js
> import { Mark, Plugin, TextSelection } from 'tiptap'
> import { getMarkRange } from 'tiptap-utils'
> 
> export default class Link extends Mark {
> 
>   // ...
> 
>   get plugins() {
>     return [
>       new Plugin({
>         props: {
>           handleClick(view, pos) {
>             const { schema, doc, tr } = view.state
>             const range = getMarkRange(doc.resolve(pos), schema.marks.link)
> 
>             if (!range) {
>               return
>             }
> 
>             const $start = doc.resolve(range.from)
>             const $end = doc.resolve(range.to)
>             const transaction = tr.setSelection(new TextSelection($start, $end))
> 
>             view.dispatch(transaction)
>           },
>         },
>       }),
>     ]
>   }
> 
> }
> ```
> 
> Maybe that helps you a bit. Instead of `handleClick` there is also a `handleDoubleClick` event ([docs](https://prosemirror.net/docs/ref/#view.EditorProps)).

you save me. many thanks. But why it's not the actual behavior of link extension?

**Comment by amursky** [comment]
What is the same solution for tiptap 2.0?

**Comment by duhaime** [comment]
@philippkuehn is there an equivalent to `editor.setSelection` in tiptap 2.0?

**Comment by bigboggy** [comment]
Still don't get how to get a specific range of a custom node

**Comment by bgoessweDedalus** [comment]
> @philippkuehn is there an equivalent to `editor.setSelection` in tiptap 2.0?
> 
> Edit: aha `editor.commands.setTextSelection({from: 1, to: 10})`

For me this seems to have issues if there is a paragraph / linebreak in between, so e.g.:

```
<p>This is a test<p>
<p>Another test<p>
```

The getText() function returns: "This is a test\n\nAnother test"
If I want to select "Another" I would expect I call setTextSelection({from: 18, to: 25}). 
But this results in selection of "nother ", so it is shifted by one, this seems to add up for each paragrah tag.
Is there a "getText" function that really correlates with the "setTextSelection" function that I can trust the positions are the same ?
Especially when there are more complex structures as enumerations and line breaks?

**Comment by bgoessweDedalus** [comment]
> @philippkuehn is there an equivalent to `editor.setSelection` in tiptap 2.0?
> 
> Edit: aha `editor.commands.setTextSelection({from: 1, to: 10})`

Hey, unfortunately, it seems that setTextSelection does not work properly in combination with the editor.toText function so the position is not correct if there are some complex elements e.g. bullet points in there, so in the toText result a bullet point is "\n\n" but it adds 4 chars to the length. e.g.: 

`
Test
- One
`
The position after "Test" is 4, the position of "One" is 8. So the bullet point adds 4 to the position, in the "toText" result it just adds 2 (\n\n), the same as for a paragraph.
Is there any function to use that returns a string that correlates at least positionwise with the setTextSelection?

**Comment by MarkusTrasberg** [comment]
> > @philippkuehn is there an equivalent to `editor.setSelection` in tiptap 2.0?
> > Edit: aha `editor.commands.setTextSelection({from: 1, to: 10})`
> 
> Hey, unfortunately, it seems that setTextSelection does not work properly in combination with the editor.toText function so the position is not correct if there are some complex elements e.g. bullet points in there, so in the toText result a bullet point is "\n\n" but it adds 4 chars to the length. e.g.:
> 
> ` Test
> 
> * One
>   `
>   The position after "Test" is 4, the position of "One" is 8. So the bullet point adds 4 to the position, in the "toText" result it just adds 2 (\n\n), the same as for a paragraph.
>   Is there any function to use that returns a string that correlates at least positionwise with the setTextSelection?
Did you manage to figure this out? 

Facing similar issue, I mostly see it with new lines. I am trying to match custom strings and add some formating to those. editor.getText() reacts quite differently than the setTextSelection when it's more than a simple block of text, seems that setTextSelection considers there to be some extra whitespace. Tried playing around with customizing the getText's blockSeparator as well as using the getHTML but no real success so far.

**Comment by bgoessweDedalus** [comment]
Actually, we didn't really find a nice solution, but the one that worked for us was a mapper function that translated the content of the tip tap editor to a text with seperator symbols for complex elements, therefore we parsed the getJSON function output (because it is a bit easier to parse in JS than HTML) and added e.g. "____" for each bullet point (actually "__" for the start of an enumeration and an additional "__" for each bullet point), so we reverse engineered how the setTextSelection positions work and adapted this "mapper". We more or less implemented our own getText function where the positioning of the text is correct. Unfortunately I can not share the code for legal reasons, but I hope this helps.
