### ISSUE TITLE
Justify Content

### ISSUE THREAD

**Issue by zymawy** [heyscrumpy/tiptap#105]
Hi, Thank You For Such Great Component. I Looked An Component But Couldn't Find The `Justify` Component. I'm Working With `Arabic Language` I Need To Make The Direction To Be From Right To Lift => `Justify RIght` How I Can I Achieve It?

**Comment by philippkuehn** [comment]
Hey, I decided to not support styling nodes in this core packages anymore. A few months ago I added a [basic example](https://github.com/heyscrumpy/tiptap/commit/cca52e0518b1324c1d05c14d3f689066aa07f56c) for alignment of paragraphs (only paragraphs). So maybe this helps you a bit.
