### ISSUE TITLE
Add support for mentions, tags & commands

### ISSUE THREAD

**Issue by philippkuehn** [heyscrumpy/tiptap#11]
Everyone needs `@mentions`, `#tags` and `/commands`. This should be possible with one extension. Rendering should be outside of tiptap.

**Comment by codepotato** [comment]
+1 for this Philip! 👍

**Comment by janiskelemen** [comment]
Hi @philippkuehn, do you have any news about this? I just looked around for a prosemirror extension and found that you have already opened an issue on prosemirror-suggestions. Did you have a chance to try this plugin? I'm willing to dig into it but wanted to check with you before.

**Comment by philippkuehn** [comment]
Hey @janiskelemen, it's the number one of my todo list. Currently I'm on vacation so I have not *that* much time to work on tiptap. `prosemirror-suggestions` is great and I already created a branch for integrating that but it's still much work to do.

**Comment by philippkuehn** [comment]
I'm making progress :)
![sep-29-2018 08-51-51](https://user-images.githubusercontent.com/2500670/46242242-91b06e80-c3c6-11e8-9db9-97b926bb1d5b.gif)

**Comment by philippkuehn** [comment]
There is a [demo](https://tiptap.scrumpy.io/suggestions) for suggestions now.

**Comment by AveryBibeau** [comment]
Thanks for putting this together. I had to modify `get name` in `nodes/Mention.js` to differentiate between mention instances since I need both @ and # as separate use cases.

Since `get name` was returning the same identifier for both instances the `this.name` in `command: ({ range, attrs, schema }) => replaceText(range, schema.nodes[this.name], attrs),` confused the two. I modified `nodes/Mention.js` like this:

```
get name() {
  return `mention-${this.options.matcher.char}`
}
```

as a quick fix and it seems to be working. Interested if anyone has used a different workaround for this.

**Comment by andreasvirkus** [comment]
@AveryBibeau Could you elaborate how you made both `@` and `#` work as triggers for the Mentions popup? Also need this 🙏

**Comment by mattwr18** [comment]
hey @AveryBibeau, I was looking at your fork and at `nodes/Mention.js` and I didn't see the code you mentioned :point_up: 
sorry if I am missing something obvious, but I didn't see how you got it working with `#` as well
We have been able to get it working with a suggestion list, but have not worked out how to get it working if there are no hashtags with the same name. We would like for the user to be able to create the hashtag if it doesn't exist already. 
Does anyone have any open-source code/demo of hashtags working with tiptap?

**Comment by andreasvirkus** [comment]
Also interested in this ☝️ 

@philippkuehn do you have any hints on how to get `#` working (with a separate source list) alongside the `@` suggestions?

**Comment by rudolfbyker** [comment]
The solution is to do what @AveryBibeau said: Subclass `Mention` and override the `name` getter.

**Comment by mattwr18** [comment]
Oh sorry, we got this worked out... here is a link to our open-source code base https://github.com/Human-Connection/Human-Connection

and the file where we do the `Hashtag` magic https://github.com/Human-Connection/Human-Connection/blob/master/webapp/components/Editor/nodes/Hashtag.js

**Comment by AbdulHussain1** [comment]
or you could just copy the exact same code from the nodemodules/tiptap-extension-mention.esm.js and change the CHAR value to whatever you want. and paste the code in a seperate JS file and export the module
