### ISSUE TITLE
Editor menu bar not working when editable change false to true on the fly

### ISSUE THREAD

**Issue by frkn-aydn** [heyscrumpy/tiptap#117]
I am changing the editable status on the fly with,

` this.editor.setOptions({editable: true});`

And its working. I can edit the content but editor menu bar not working. Buttons coming without error but when i change the editable state false to true, its not working. Its only working without editable state changing. 

How can i fix this issue ?

**Comment by philippkuehn** [comment]
duplicate of #111

**Comment by MarvinMiles** [comment]
Hey @philippkuehn

Still does't work. After setting `editor.setOptions({editable: true})` I can't edit content using buttons in   menu bar (make it Bold for example).

version 1.7.0
