### ISSUE TITLE
How to remove paragraph in ListItem

### ISSUE THREAD

**Issue by GERJohnson** [heyscrumpy/tiptap#118]
Hi, 

For ordered & bullet lists the content of the LI tag is wrapped in a paragraph.

I need to remove the paragraph to style the dot but I don't find where the P tag is created.

I already tried to remove the paragraph tag in [ListItem.js](https://github.com/heyscrumpy/tiptap/blob/master/packages/tiptap-extensions/src/nodes/ListItem.js) file but it doesn't have any affect. 

How can I remove the paragraph tag for list items?

Thanks,
Johnson

**Comment by philippkuehn** [comment]
Hey, this is related to ProseMirror. I'm not sure if this is possible. Try to ask that in the offical [forum](https://discuss.prosemirror.net/).

**Comment by bernhardh** [comment]
@GERJohnson: Any updates on this? Have you found a solution? Its really anoying, to wrap listems into `p` tags

**Comment by Hyperblaster** [comment]
Yep, would love to know too!

**Comment by GERJohnson** [comment]
No.. the P tag is one of the worst feature of ProseMirror... Also got no reply in ProseMirror forum. I ended up hacking the P tag with CSS to my needs for lists..

**Comment by philippkuehn** [comment]
@GERJohnson Basically it’s because a list item can contain multiple block elements (text blocks, nested lists, whatever). To change that, you’ll have to rewrite some parts of `prosemirror-schema-lists`. But it‘s open source. You‘re free to create pull requests.

**Comment by renielDev** [comment]
any updates on this? @philippkuehn 

thanks

**Comment by usb248** [comment]
Still an issue..........

**Comment by hanspagel** [comment]
And it’s still how ProseMirror works, so nothing we can do here. 💫

**Comment by rgfretes** [comment]
Hi , I manage to found a solution to this creating a custom list item extension 

`import ListItem from '@tiptap/extension-list-item'

const CustomListItem = ListItem.extend({
  content: 'text*',
  renderHTML({ HTMLAttributes }) {
    // Original:
    // return ['li', core.mergeAttributes(this.options.HTMLAttributes, HTMLAttributes), 0];
    console.log("HTMLAttributes", HTMLAttributes)
    return ['li', {}, 0]
  },
})

export default CustomListItem;`

**Comment by Mushr0000m** [comment]
Still an issue

**Comment by paceaux** [comment]
For anyone who still this problem, I've found a [solution ](https://discuss.prosemirror.net/t/removing-the-default-paragraph-p-inside-a-list-item-li/2745/14)that worked for me without much hackery. It requires extending an element and adding that extension to extensions. 

First, get `ListItem`

```
import ListItem from '@tiptap/extension-list-item';
```

next, extend it by setting it to only allow text content ([TipTap was nice enough to explain what can go in there](https://tiptap.dev/api/schema))

```
const CustomListItem = ListItem.extend({
    content: 'text*'
});
```

Finally, add it in to your editor (note: this is for Vue)

```
mounted() {
  this.editor = new Editor({
    extensions: [
      StarterKit.configure({
        history: true,
      }),
      CustomListItem,
    ],
  });
}
```

**Comment by philippkuehn** [comment]
@paceaux Keep in mind that it’s not possible to use nested lists with that configuration.

**Comment by paceaux** [comment]
@philippkuehn  Yep it's a limited solution. But in my case where I really needed existing data to not be corrupted, it worked.  I'm building editing tools for a content management system and we needed specifically single-level lists. 

I understand that this is ProseMirror's problem and not TipTap's, but this issue was going to affect upwards of 15,000 records.  It would be great if this issue was in the TipTap documentation with recommended solutions.

**Comment by ixam1** [comment]
@paceaux I have the same problem and this solution unfortunately doesnt work for me. Extending `ListItem` with `content: 'text*'` makes the List Button unusable for me. I can extend with `content: 'block*'` though (which doesnt help, but I think shows that I "extend correctly")

Could you please show the rest of your code, or anything that might influence why this solution is working for you, but not for me? Thanks in advance!

Here is my code:

```
import React, { useState } from "react"
import { useEditor, EditorContent } from "@tiptap/react"
import StarterKit from "@tiptap/starter-kit"
import Placeholder from "@tiptap/extension-placeholder"
import Underline from "@tiptap/extension-underline"
import ListItem from "@tiptap/extension-list-item"

export default ({ value, onChange, placeholder, error, readOnly}) => {
	const editor = useEditor(
		{
			extensions: [
				StarterKit.configure(),
				ListItem.extend({
					content: "text*",
				}),
				Placeholder.configure({
					placeholder: placeholder,
				}),
				Underline,
			],
			content: value,
			editable: !readOnly,
			onUpdate: ({ editor }) => {
				console.log(editor.getHTML())
				onChange?.(editor.getHTML())
			},
		},
		[value, onChange, placeholder, readOnly]
	)

	return (
		<div>
			<div>
				<button
					onClick={() => editor.chain().focus().toggleBulletList().run()}
				>
					UL
				</button>
				<button
					onClick={() => editor.chain().focus().toggleOrderedList().run()}
				>
			                OL
				</button>
			</div>
			<div className={error ? "text-red-900" : ""}>
				<EditorContent editor={editor} />
			</div>
		</div>
	)
}

**Comment by mbrodala** [comment]
Not sure why this issue was closed while it is still present.

I can confirm that extending the `ListItem` to restrict its `content` to plain text does not work. Maybe because there is always a paragraph by default and TipTap always wraps the current node (paragrahp here) on `toggle*List*()`? Then of course wrapping a paragraph with a list item would be forbidden due to the `content` restriction.

**Comment by alexcroox** [comment]
The workaround for me where I only cared about the <p> inside the <li> because of margin issues:

```
.prose {
  & li > p {
    margin: 0;
  }
}
```

`prose` being whatever class wraps your content (for me it's tailwindcss/typography)

**Comment by AndrwM** [comment]
Hey all,

Here's an alternative solution that utilizes a `<span>` instead of a `<p>`. In my use case I don't have control over the styling of the html.

```javascript
import ListItem from '@tiptap/extension-list-item';

export default ListItem.extend({
  content: 'listItemContent block*',
});
```

```javascript
import { Node, mergeAttributes } from '@tiptap/core';

export default Node.create({
  name: 'listItemContent',
  group: 'block',
  content: 'inline*',

  parseHTML() {
    return [
      {
        tag: 'span',
        getAttrs: (element) => {
          if (element.parentNode.tagName === 'LI') {
            return null;
          }
          return false;
        },
      },
    ];
  },

  renderHTML({ HTMLAttributes }) {
    return ['span', mergeAttributes(this.options.HTMLAttributes, HTMLAttributes), 0];
  },
});
```

I hope this helps someone. All the best 🌿

**Comment by miks** [comment]
@AndrwM can you create new lists with your solution? It's working as expected (replacing `<p>` with `<span>`) within existing list, but I can't create new lists anymore.

**Comment by vaban-ru** [comment]
Hello guys, area there any solutions tto remove paragraph from li?

**Comment by suchintan** [comment]
This worked for me:
```
    "ul,ol": {
      padding: "0 1rem",
      p: {
        margin: 0,
      },
    },
```

**Comment by vaban-ru** [comment]
> This worked for me:
> 
> ```
>   ".ProseMirror": {
>     "ul,ol": {
>       padding: "0 1rem",
>       p: {
>         margin: 0,
>       },
>     },
> }
> ```

Thnx, but I need to remove it from html, not just visual

**Comment by volkandkaya** [comment]
> @AndrwM can you create new lists with your solution? It's working as expected (replacing `<p>` with `<span>`) within existing list, but I can't create new lists anymore.

Did you (@miks ) or @AndrwM  get it working? It seems to be an issue with replacing the paragraph with span.

https://github.com/ueberdosis/tiptap/blob/main/packages/extension-list-item/src/list-item.ts
https://github.com/ueberdosis/tiptap/blob/main/packages/extension-paragraph/src/paragraph.ts
https://github.com/ueberdosis/tiptap/blob/main/packages/extension-bullet-list/src/bullet-list.ts
https://github.com/ueberdosis/tiptap/blob/312866044ac74dd980a412305cc0e435e1f016e5/packages/core/src/commands/toggleList.ts#L73

**Comment by miks** [comment]
@volkandkaya no, we are using https://github.com/cube-agency/nova-tinymce now

**Comment by volkandkaya** [comment]
@miks just spent the morning replacing my old library that works fine (because I'm using Mantine who decided to swap to Tiptap).

I will "hack" it with CSS I guess, until it is fixed or the feature is added.

**Comment by jgelens** [comment]
I just remove the paragraphs from the generated HTML:
`html.replaceAll(/<li><p>(.*?)<\/p><(\/?)(ol|li|ul)>/gi, "<li>$1<$2$3>")`

**Comment by katerlouis** [comment]
> @paceaux I have the same problem and this solution unfortunately doesnt work for me. Extending `ListItem` with `content: 'text*'` makes the List Button unusable for me. I can extend with `content: 'block*'` though (which doesnt help, but I think shows that I "extend correctly")

Have you found a solution?

@paceaux It's weird; during playing around I got it to work once; but I don't know what I'm doing differently right now? I guess it must have something to do with Hot-Module replacement?

**Comment by Sliffcak** [comment]
Curious if any official news on this also. Would be great to not have list items wrapper in a paragraph.

**Comment by stouch** [comment]
We wanted to remove the `<p>` inside the `<li>` but I realized this meant that to get rid of nested `<ul>` inside the `<li>`. 

So the extension should only allow 1-level of <ul><li>inline text</li></ul> and not any ul children in <li>, so disable the Tab command etc..

Anyway, I realize I had to recreate a complete custom BulletList extension and I prefered the @ixam1 solution.

**Comment by sistrix-geant** [comment]
I have been searching for a way to remove the `<p>` element created in `<li>` items for a few days, but to no avail.
However, after reading a little in the documentation, i was able to successfully remove the paragraph from list items only.

It is quite simple, too.

This is how I did it:
```javascript
const editor = new Editor({
        el: document.querySelector('#editor'),
        initialEditType: 'markdown',
        customHTMLRenderer: {
            paragraph: function(node, context) {
                if (node.parent.type === 'item') {
                    return null;
                }
                return {
                    type: context.entering ? 'openTag' : 'closeTag',
                    tagName: 'p',
                };
            }
        },
        autofocus: false,
    });
```

In essence, simply ignore `<p>` creation if the parent is of type `item`.

Hope this helps!

**Comment by sistrix-geant** [comment]
Just realized this only removes the `<p>` from the preview, unfortunately. The result using `editor.getHTML()` still has paragraphs.

So I see the problem now. Couldn't have been this easy

**Comment by hmdegroot** [comment]
Seeing this problem today. I worked around it with the following:

```
/// my editor is setup as such:
const TipTapEditor: React.FC<TipTapEditorProps> = ({ field }) => {
  const editor = useEditor({
    extensions: [
      StarterKit,
      Underline,
      Heading.configure({ levels: [1, 2, 3, 4, 5, 6] }),
      Link,
      BulletList.configure({
        HTMLAttributes: {
          class: 'ml-4'
        },
        keepAttributes: false
      }),
      TextAlign.configure({
        types: ['heading', 'paragraph'],
      }),
    ],
    editorProps: {
      attributes: {
        class: cn(`px-3 py-2 min-h-[200px] 
                border border-input rounded-b-md border-input shadow-sm
                focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring
                focus:outline-none
                hover:border-contentTertiary`)
      }
    },
    onUpdate: ({ editor }) => {
      const newContent = editor.getHTML();
      if (newContent !== field.value) {
        field.onChange(newContent);
      }
    },
  });
    
//on my toolbar I'm importing custom styles in, don't love this but it works 
.tipTap {
	ul {
		list-style-type: disc;
	}
}

//my element passed into my toolbar
  <button
        onClick={() => editor.chain().focus().toggleBulletList().run()}
        className={editor.isActive('bulletList') ? 'is-active' : ''}>
        <ListBulletIcon />
      </button>
```

**Comment by gurnro** [comment]
If you are using tailwind and don't care about the P tags being there you can do this to fix the issue.

`ListItem.configure({
      HTMLAttributes: {
         class: "[&>p]:inline-block",
      },
 }),`

**Comment by thyco** [comment]
We didn't want to depend on css classes, so we used this solution.

What this does is add the style "margin: 0" if the "p" tag is inside the list, otherwise "margin: revert" to fallback to the default of the browser.

`Paragraph.extend({
        addAttributes() {
          return {
            ...this.parent?.(),
            style: {
              parseHTML: element => element?.parentElement?.tagName === "LI" ? "margin: 0" : "margin: revert"
            }
          }
        },
      }),`

**Comment by thyco** [comment]
I tried to do the following: set margin to 0 if the parent is a list item otherwise the default browser margin.
This works when loading existing content in the editor, but when adding paragraphs with enter, the parseHTML function does not get execute and you end up with random 0 or revert.

````
Paragraph.extend({
  addAttributes() {
    return {
      ...this.parent?.(),
      style: {
        parseHTML: element => element?.parentElement?.tagName === "LI" ? "margin: 0" : "margin: revert"
      }
    }
  },
}),
````

Maybe using renderHTML could be a solution, but it doesn't seem possible to access the element, so it's not possible to find out if the paragraph is inside a list item or not. Anyone got any idea to do this?

**Comment by MickL** [comment]
@philippkuehn Can this be reopened? There should be no <p> inside lists imo.

**Comment by zejefferson** [comment]
I'm also struggling with this issue right now and I'd be glad if this could be re-opened. 

Forcing the <p> tag doesn't seem to create any benefit (and it's using to create it programmatically if needed) but it makes it more difficult to style list items (for instance with list-style-position: inside).

**Comment by alexbaramilis** [comment]
I also think this should not be closed and on the other hand there should be some official guidance in the documentation on how to get around this. Imo lists are broken without a workaround. I spent two days trying to get them to work and almost switched to another RTE in the process. I only came back because I didn't like the other editor and because of stubborness.

Anyway, here's my two fixes. I'm using Svelte and Tailwind btw. I also don't care about nested lists.

The simplest one, if you want to use the default formatting:

`BulletList.configure({
    HTMLAttributes: {
        class: 'list-disc list-inside'
    }
}),
ListItem.configure({
    HTMLAttributes: {
        class: '*:inline pl-2.5'
    }
})`

My issue with this one is you can't tweak the markers and they are not exactly centered, but if you're not a perfectionist it works fine.

If you want to customise a bit more, you can use your own marker like:

`BulletList,
ListItem.configure({
    HTMLAttributes: {
        class: "flex before:content-['•'] before:text-5xl before:mr-2.5 before:-my-[9px]"
    }
})`

With this one you can play with the marker text, size and spacing.

**Comment by MickL** [comment]
I think the problem is that TipTap is not an actual editor. The actual editor is ProseMirror and TipTap is just something on top of it. And since the issue is from ProseMirror they say its not their problem.

**Comment by JThompson-VI** [comment]
My solution was to patch the html before sending it to the backend:
```js
function patchTipTapHTML(content: string | null) {
  if (content === null) return null;

  const parser = new DOMParser();
  const doc = parser.parseFromString(content, 'text/html');

  const listItems = doc.querySelectorAll('li');
  listItems.forEach((li) => {
    const p = li.querySelector('p');
    if (p) {
      while (p.firstChild) {
        li.insertBefore(p.firstChild, p);
      }
      p.remove();
    }
  });
  return doc.body.innerHTML;
  }
```

**Comment by alanpoulain** [comment]
A first version of a solution to make it work (it probably doesn't work for nested lists though).

```ts
import { getNodeType } from "@tiptap/core";
import TipTapListItem from "@tiptap/extension-list-item";
import { Fragment, NodeType } from "@tiptap/pm/model";

function changeChildNodeTypes(content: Fragment, sourceTypeName: string, targetType: NodeType): Fragment {
  let newContent = content;

  for (let i = 0; i < content.childCount; i++) {
    const node = content.child(i);

    if (node.type.name === sourceTypeName) {
      const listItem = targetType.create(node.attrs, node.content, node.marks);
      newContent = newContent.replaceChild(i, listItem);
    }
  }

  return newContent;
}

export const ListItem = TipTapListItem.extend({
  content: "text*",

  addCommands() {
    return {
      liftListItem:
        () =>
        ({ state, dispatch }) => {
          const paragraphType = getNodeType("paragraph", state.schema);

          const { tr } = state;

          const { $from, $to } = tr.selection;
          const range = $from.blockRange($to);

          if (!range) return false;

          const content = tr.doc.slice(range.start, range.end).content;

          const paragraphs = changeChildNodeTypes(content, "listItem", paragraphType);

          if (dispatch) {
            tr.replaceWith(range.start - 1, range.end, paragraphs);

            dispatch(tr);
          }

          return true;
        },
      wrapInList:
        (typeOrName, attributes = {}) =>
        ({ state, dispatch }) => {
          const listType = getNodeType(typeOrName, state.schema);
          const listItemType = getNodeType("listItem", state.schema);

          const { tr } = state;

          const { $from, $to } = tr.selection;
          const range = $from.blockRange($to);

          if (!range) return false;

          const content = tr.doc.slice(range.start, range.end).content;

          const listItems = changeChildNodeTypes(content, "paragraph", listItemType);

          const listNode = listType.create(attributes, listItems);

          if (dispatch) {
            tr.replaceWith(range.start, range.end, listNode);

            dispatch(tr);
          }

          return true;
        },
    };
  },
});
```
