### ISSUE TITLE
Extensions as per examples don't actually do anything

### ISSUE THREAD

**Issue by codepotato** [heyscrumpy/tiptap#13]
Hey, firstly thanks for such an awesome editor. Love it! 

However, I cannot seem to get any of the built in extensions to actually run. I've got an instance setup with a simple editor and the same code as the hidden menubar example but when I click to edit the code (bold, for example) the menubar disappears but nothing happens to the code. Calling the update method to grab the built html returns code without the additional formatting. 

Any pointers?

**Comment by codepotato** [comment]
`<template lang="html">
    <div class="chat-composer" id="chat-composer">
        <div class="columns">
            <div class="column">

                <editor :extensions="extensions" @update="onUpdate">
                    <div class="menubar" :class="{ 'is-focused': focused }" slot="menubar" slot-scope="{ nodes, marks, focused }">
                        <div v-if="nodes && marks">

                            <button
                                class="button is-white is-small"
                                :class="{ 'is-active': marks.bold.active() }"
                                @click="marks.bold.command"
                            >
                                <icon name="bold"/>
                            </button>

                            <button
                                class="button is-white is-small"
                                :class="{ 'is-active': marks.italic.active() }"
                                @click="marks.italic.command"
                            >
                                <icon name="italic"/>
                            </button>

                            <button
                                class="button is-white is-small"
                                :class="{ 'is-active': nodes.paragraph.active() }"
                                @click="nodes.paragraph.command"
                            >
                                <icon name="paragraph"/>
                            </button>

                            <button
                                class="button is-white is-small"
                                :class="{ 'is-active': nodes.heading.active({ level: 1 }) }"
                                @click="nodes.heading.command({ level: 1 })"
                            >
                                H1
                            </button>

                            <button
                                class="button is-white is-small"
                                :class="{ 'is-active': nodes.heading.active({ level: 2 }) }"
                                @click="nodes.heading.command({ level: 2 })"
                            >
                                H2
                            </button>

                            <button
                                class="button is-white is-small"
                                :class="{ 'is-active': nodes.heading.active({ level: 3 }) }"
                                @click="nodes.heading.command({ level: 3 })"
                            >
                                H3
                            </button>

                            <button
                                class="button is-white is-small"
                                :class="{ 'is-active': nodes.bullet_list.active() }"
                                @click="nodes.bullet_list.command"
                            >
                                <icon name="list-ul"/>
                            </button>

                            <button
                                class="button is-white is-small"
                                :class="{ 'is-active': nodes.ordered_list.active() }"
                                @click="nodes.ordered_list.command"
                            >
                                <icon name="list-ol"/>
                            </button>


                        </div>
                    </div>
                    <div slot="content" slot-scope="props">
                        <p>Write your message here.</p>
                    </div>
                </editor>

                
                
                <div class="file has-name">
                    <label class="file-label">
                        <input type="file" class="file-input" id="file" multiple ref="file"
                               v-on:change="handleFileUpload()"/>
                        <span class="file-cta">
                          <span class="file-icon">
                            <i class="fal fa-upload"></i>
                          </span>
                          <span class="file-label">
                            Choose a file…
                          </span>
                        </span>
                        <span class="file-name">
                            {{ temp_filename }}
                        </span>
                    </label>
                </div>
            </div>
            <div class="column is-narrow">
                <a class="button is-large" @click="sendMessage">Send</a>
            </div>
        </div>
    </div>
</template>

<script>
    import {Editor} from 'tiptap'
    import {
        BlockquoteNode,
        BulletListNode,
        CodeBlockNode,
        HardBreakNode,
        HeadingNode,
        ImageNode,
        ListItemNode,
        OrderedListNode,
        TodoItemNode,
        TodoListNode,
        BoldMark,
        CodeMark,
        ItalicMark,
        LinkMark,
        HistoryExtension,
    } from 'tiptap-extensions'

    export default {
        data() {
            return {
                messageText: '',
                file: [],
                temp_filename: '',
                extensions: [
                    new BlockquoteNode(),
                    new BulletListNode(),
                    new CodeBlockNode(),
                    new HardBreakNode(),
                    new HeadingNode({maxLevel: 3}),
                    new ImageNode(),
                    new ListItemNode(),
                    new OrderedListNode(),
                    new TodoItemNode(),
                    new TodoListNode(),
                    new BoldMark(),
                    new CodeMark(),
                    new ItalicMark(),
                    new LinkMark(),
                    new HistoryExtension(),
                ],

            }
        },

        components: {
            Editor,
        },

        mounted() {

        },
        methods: {
            sendMessage() {
                this.$emit('messagesent', {
                    message: this.messageText,
                });
                console.log( this.messageText );
                this.messageText = '';
            },
            handleFileUpload() {
                this.file = this.$refs.file.files;
                if (this.file.length === 1) {
                    this.temp_filename = this.file[0].name;
                } else if (this.file.length > 1) {
                    this.temp_filename = this.file.length + ' files';
                } else {
                    this.temp_filename = '';
                }

                this.$emit('filesadded', {
                    files: this.file,
                });
            },
            onUpdate({getJSON, getHTML}){
                this.messageText = getHTML();
            }
        }
    }
</script>
`
This is my vue component / code in case that helps.

**Comment by codepotato** [comment]
This is my component's code at the moment : 

https://gist.github.com/codepotato/f68b6e3625f3a35908a7e9857bab1298

**Comment by philippkuehn** [comment]
Hey, thank you for testing tiptap. I tested your code and it looks fine for me. Is the examples page working for you? Maybe you could tell me which browser you are using and provide a test setup ([codesandbox](https://codesandbox.io) would be nice).

**Comment by philippkuehn** [comment]
Ah, good point! I think the problem is that when you click on the menu the editor blurs and the menu will be hidden before you could click the button. In my examples I‘m using a transition so even when `focus` is set to `false` the menu will be shown for some time. You could fix that with also set a transition or hiding the menu with `opacity: 0`.

**Comment by codepotato** [comment]
You're a legend @philippkuehn. Spot on. 

Needed something like the following: 
`.menubar{
    background: #f7f7f7;
    border-radius: 0.2rem;
    visibility: hidden;
    padding: 0.3rem;
    position: absolute;
    opacity: 0;
    top: -30px;
    left: 15px;
    transition: visibility 0.2s ease 0.4s, opacity 0.2s ease 0.4s;

    &.is-focused{
        visibility: visible;
        opacity: 1;
    }
}
`

**Comment by philippkuehn** [comment]
You don't need a transition anymore with this fix: https://github.com/scrumpy/tiptap/commit/21891519031ee724b33acfd1e8c28e5c98eced9d
