### ISSUE TITLE
Android: Node type updates only after starting to type

### ISSUE THREAD

**Issue by hanspagel** [heyscrumpy/tiptap#2]
When I toggle/switch node types no change is visible. I have to start typing to see the change.

I would expect an instant update of the node type.

Screenrecording
![ezgif-4-71baead24e](https://user-images.githubusercontent.com/1577992/44632992-ed7d7700-a984-11e8-9e6a-800b9c079977.gif)

**Comment by philippkuehn** [comment]
This is a bug by Prosemirror itself.
