### ISSUE TITLE
0.11.1 throws error while serializing HTML via getHTML()

### ISSUE THREAD

**Issue by nodegin** [heyscrumpy/tiptap#25]
I have custom Node, Mark in my project, after upgrading to version 0.11.1 the following error will be thrown:

```
index.js:3296 Uncaught TypeError: this.nodes[node.type.name] is not a function
    at DOMSerializer.serializeNode (index.js:3296)
    at index.js:3280
    at Fragment.forEach (index.js:242)
    at DOMSerializer.serializeFragment (index.js:3256)
    at DOMSerializer.serializeNode (index.js:3305)
    at index.js:3280
    at Fragment.forEach (index.js:242)
    at DOMSerializer.serializeFragment (index.js:3256)
    at VueComponent.getHTML (tiptap.esm.js:773)
    at VueComponent.beforeSubmit (index.vue?e4fa:898)
```

**Comment by philippkuehn** [comment]
Can you show me the schema of your custom nodes and marks?

**Comment by nodegin** [comment]
It looks like this:

```
class EmojiNode extends Node {
  get name() {
    return 'emoji'
  }

  get view() {
    return {
      props: ['node'],
      render(h) {
        const { code } = this.node.attrs
        return h('div', {
          attrs: {
            'class': 'emoji',
          },
          domProps: {
            innerHTML: code
          },
        })
      },
    }
  }

  get schema() {
    return {
      attrs: {
        code: { default: null },
      },
      inline: true,
      group: 'inline',
      draggable: false,
      parseDOM: [
        {
          tag: 'div[class="emoji"]',
          getAttrs: (dom) => ({
            code: dom.innerHTML,
          }),
        },
      ],
    }
  }

  command({ type, attrs }) {
    return (state, dispatch) => {
      dispatch(state.tr.replaceSelectionWith(type.create(attrs)))
    }
  }
}
```

I am using v0.11.0 now and it is working fine for me

**Comment by philippkuehn** [comment]
Ah okay. With 0.11.1 I changed to way how HTML will be exported. I'm now using a function that do not export any decorations of prosemirror. (decorations are changes to the DOM, like search highlighting or code highlighting that should not be part of your exported HTML). For doing that the `toDOM()` function is still required in your schema (even if you render your nodes and marks as a vue component). This can be very basic, so `parseDOM()` is able to parse it later.

I recommend to use vue components only if you want to do some dynamic changes or want to interact with your nodes.

btw: `toDOM()` is also required for copy and paste to work.
