### ISSUE TITLE
placeholder text doesn't disappear if the user leaves first line of editor blank

### ISSUE THREAD

**Issue by jaysaurus** [heyscrumpy/tiptap#26]
I'm guessing your query selector checks for an empty `<p></p>` on the first line of the editor :) the bad news is, that doesn't necessarily mean the editor is empty haha!  

![placeholderbug](https://user-images.githubusercontent.com/31482441/45506556-8682ff00-b787-11e8-89ab-0b28f7baa6f9.gif)

**Comment by codepotato** [comment]
Whilst I agree this is a bit clumsy, the practical applications seem a little unlikely. Most systems would strip out the empty tags before saving to the database etc.

**Comment by jaysaurus** [comment]
It wouldn't even get to the server as it's content rendered from a ::before tag! Given tiptap is arguably the best solution to content-editable in vue, I think it's worth the fix. Tell you what, I'll fork and have a look see if I can spot the problem :)

**Comment by philippkuehn** [comment]
In this moment I try to fix that :) What would you expect?
- the placeholder should be visible if the editor is completely empty?
- the placeholder should be visible only on the current line (where the cursor is active)?
- or should I add classes for each of these cases?

**Comment by codepotato** [comment]
If the editor is completely empty, like a regular placeholder on an input, I reckon. 👍

**Comment by jaysaurus** [comment]
As code potato says. I think it should work like the placeholder on the text boxes we're currently having this conversation with! :D 

Thank you for such a quick response Phillip!

**Comment by philippkuehn** [comment]
Hmm. I've seen a use case for line based placeholders at Notion!

![sep -13-2018 22-11-33](https://user-images.githubusercontent.com/2500670/45513130-22216900-b7a2-11e8-9342-f39ca04494fa.gif)

Maybe I should provide classes for each cases.

**Comment by jaysaurus** [comment]
Hiya, related theme, some more weird behaviour!
![placeholderbug](https://user-images.githubusercontent.com/31482441/45513903-dd92cf00-b79b-11e8-8ef3-2907158e4920.gif)

**Comment by philippkuehn** [comment]
The placeholder is only visible for completely empty documents for now. @jaysaurus with v0.12.1 you also do not have to change any CSS.

**Comment by jaysaurus** [comment]
Good job! Thanks!

**Comment by usb248** [comment]
Are you sure of what you said ? 🤔  Still very weird behavior ....
![image](https://user-images.githubusercontent.com/7659927/64896760-3b911580-d681-11e9-985f-6c6f32f00d00.png)
