### ISSUE TITLE
change doc dynamically 

### ISSUE THREAD

**Issue by kopipejst** [heyscrumpy/tiptap#29]
it would be great to have something similar to `this.$refs.editor.clearContent()` that we can use to replace doc dynamically. eg. `this.$refs.editor.replaceDoc(doc)`

**Comment by philippkuehn** [comment]
I already thought about this. Would it solve your problem if `doc` were reactive? Currently the editor do not update itself whenever the `doc` prop changes.

**Comment by kopipejst** [comment]
that would solve the problem definitely. 
I tried destroyEditor() change doc and initEditor(), but since it happens in the same cycle things didn't work as expected : )

**Comment by wizpig64** [comment]
A reactive doc prop would solve the same issue for my wiki project, which lets the user view older versions of the page and does so by modifying that prop.

Calling the `destroyEditor` and `initEditor` hooks fixed this issue for me in my project, but it would always render doc from one click ago, rather than the one on the current click, if that makes sense. I fixed that with `this.$nextTick`, like so:

```
<template>
  ...
  <tiptap-editor ref="editor"
          :doc="document"
          :editable="!history_id"
          :extensions="tiptap_extensions"
          @update="editor_update">
    <div slot="content" slot-scope="props"></div>
  </tiptap-editor>
  ...
</template>
<script>
export default {
  name: 'MyEditorWrapper',
  components: {
    Editor
  },
  props: ['document'],
  methods: {
    refreshEditor() {
      this.$nextTick(() => {
        this.$refs.editor.destroyEditor()
        this.$refs.editor.initEditor()
      })
    },
    /// ...
  },
  watch: {
    document() {
      if (!this.unsaved_changes) {
        this.refreshEditor()
      }
    }
  }
}
</script>
```

**Comment by philippkuehn** [comment]
In v0.12.0 the editor re-renders on changes to `doc`. There is also a `setContent()` function if you want to update the content manually (`this.$refs.editor.setContent(doc)`).

**Comment by kopipejst** [comment]
thank you for fast response.
I have one small suggestion, maybe emitUpdate should be false by default. I'm not sure that replacing the doc is same as update.

**Comment by philippkuehn** [comment]
Good point! Wasn‘t sure about this one. Will change it.

**Comment by philippkuehn** [comment]
In v0.12.1 it is set to `false` by default
