### ISSUE TITLE
Insert image to the editor

### ISSUE THREAD

**Issue by reksiars** [heyscrumpy/tiptap#36]
Hi,
I want to insert a image to the editor, i found `setContent` in this link (https://tiptap.scrumpy.io/export) but this code will replace all the text on my editor. Is there another function to append the image to the editor?
Thanks in advance.

**Comment by reksiars** [comment]
I also tried this code, but still not worked for me.

```
<input type="file" ref="uploadImage" @change="onFileSelected($event.target.files, nodes.image, focus)" style="display: none">

var urlImage= 'https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png'
type.command({ src: urlImage, alt: urlImage, title: urlImage })
```

**Comment by Rolanddoda** [comment]
Try `<img src="image_url_here" />`

**Comment by reksiars** [comment]
I can append the picture using push array and `setContent`. But i don't know is this the best way or not.
Someone can help me to review my code, your help will be appreciated.
Thanks.

```
...
<editor class="editor form-control form-control-lg p-0 m-0" :extensions="extensions" @update="onUpdate" ref="editor">
	...
</editor>

<button @click="onSetContent()"><i class="fas fa-image"></i></button>

...

export default {
	nowContent: null
},
mounted () {
	this.nowContent = {
		type: 'paragraph',
		content: []
	}
},
methods: {
	onUpdate ({getHTML, getJSON}) {
		this.nowContent = getJSON()
	},
	onSetContent () {
		this.nowContent['content'].push({
			type: 'paragraph',
			content: [
				{
					attrs: {
						src: 'https://avatars1.githubusercontent.com/u/43021993?s=88&v=4'
					},
					type: 'image'
				}
			]
		})
		this.$refs.editor.setContent(this.nowContent, false)
	}
}
```

**Comment by philippkuehn** [comment]
Please do not use `setContent` for adding content. It was introduced for replacing the document. But you are right – there was no command for inserting images. I also improved [the demo page](https://tiptap.scrumpy.io/images) for adding images. Hope that helps.

**Comment by reksiars** [comment]
Thanks for your help @philippkuehn :+1::+1:
