### ISSUE TITLE
Tested on iOS?

### ISSUE THREAD

**Issue by stefandevo** [heyscrumpy/tiptap#37]
Nice component, but this component needs some more testing on mobile devices I think.
At least on iOS, the Menu Bubble sample does not work -> when you select something on iOS there is a native popup already hiding the Menu Bubble.

**Comment by philippkuehn** [comment]
Yeah of course. I wouldn’t use a bubble menu for mobile at all. It‘s up to you to build a fallback or use a regular menu bar.
