### ISSUE TITLE
[Question] Custom data attributes on mentions

### ISSUE THREAD

**Issue by OwenMelbz** [heyscrumpy/tiptap#46]
Hi,

Loving the package so far! Was all going swimmingly until we hit a bit of a complication.

We've provided a list of `Mentionables` to the component, which are sources from various locations, e.g Admins, Authors, Doctors, Nurses etc.

We provide the object similar to 

```js
[{
    "id": 1,
    "label": "Some name",
    "type": "Admin"
}]
```
-- 

Our backend needs to know the type of Mentionable so it can locate them from the correct data source to setup notifications etc - however when we get the final HTML it looks something like

```
"<p><span class="mention" data-mention-id="4">@Mr Something</span> woo woo</p>"
```

However it only has the ID and Name - Ideally we want to have something like `data-type="Admin"` so our backend can parse the code and know what type of Mentionable this was.

--

How would we go about adding the extra information to the HTML that it returns?

Thanks :)

**Comment by philippkuehn** [comment]
Hey @OwenMelbz. I already thought about adding a `type` prop to mentions but mostly it's probably not needed!? 🤷‍♂️

You can extend the default `MentionNodeExtension`. Just make a copy from `tiptap-commands` and add custom attributes. For doing this you only have to make some changes in `schema()` like this:

```js
import { Node } from 'tiptap'
import { replaceText } from 'tiptap-commands'
import { SuggestionsPlugin } from 'tiptap-extensions'

export default class MentionNode extends Node {

	get name() {
		return 'mention'
	}

	get defaultOptions() {
		return {
			matcher: {
				char: '@',
				allowSpaces: false,
				startOfLine: false,
			},
			mentionClass: 'mention',
			suggestionClass: 'mention-suggestion',
		}
	}

	get schema() {
		return {
			attrs: {
				id: null,
				label: null,
				type: null,
			},
			group: 'inline',
			inline: true,
			selectable: false,
			atom: true,
			toDOM: node => [
				'span',
				{
					class: this.options.mentionClass,
					'data-mention-id': node.attrs.id,
					'data-mention-type': node.attrs.type,
				},
				`@${node.attrs.label}`,
			],
			parseDOM: [
				{
					tag: 'span[data-mention-id]',
					getAttrs: dom => {
						const id = dom.getAttribute('data-mention-id')
						const type = dom.getAttribute('data-mention-type')
						const label = dom.innerText.split('@').join('')
						return { id, type, label }
					},
				},
			],
		}
	}

	get plugins() {
		return [
			SuggestionsPlugin({
				command: ({ range, attrs, schema }) => replaceText(range, schema.nodes.mention, attrs),
				appendText: ' ',
				matcher: this.options.matcher,
				items: this.options.items,
				onEnter: this.options.onEnter,
				onChange: this.options.onChange,
				onExit: this.options.onExit,
				onKeyDown: this.options.onKeyDown,
				onFilter: this.options.onFilter,
				suggestionClass: this.options.suggestionClass,
			}),
		]
	}

}
```

**Comment by philippkuehn** [comment]
@OwenMelbz is this resolved? :)

**Comment by OwenMelbz** [comment]
Hey @philippkuehn sorry I've not had a chance to check :) have been on other stuff! Feel free to close it, It can always be re-opened if needed :D

**Comment by philippkuehn** [comment]
Thanks!

**Comment by Haraldson** [comment]
Hey @philippkuehn! Is this still the recommended way of accommodating for more props, or is there an easier way to override/extend the official Mention plugin I should look into instead?

**Comment by bannarisoftwares** [comment]
Did you got any solution for this feature @Haraldson ?
