### ISSUE TITLE
Links not clickable

### ISSUE THREAD

**Issue by ijump** [heyscrumpy/tiptap#47]
Hi,

Thanks for this great library! Quick question/issue below.

Links on demo site are not clickable under the Links demo. Is this intentional? Part of the editing mode? I tried in a local test example, and same effect.

Thanks
Steve

**Comment by philippkuehn** [comment]
Yeah, this is intentional behavior for edit mode. You can see that in [read mode](https://tiptap.scrumpy.io/read-only) all links are clickable. For opening links in edit mode you could extend the default `LinkMarkExtension` and add a tooltip or something.
