### ISSUE TITLE
Add vue as a peerDependency

### ISSUE THREAD

**Issue by simonme** [heyscrumpy/tiptap#48]
Hi,
awesome library!

It would be great if `vue` was added to the `tiptap` package as a `peerDependency`, because it is required in `packages/tiptap/src/utils/ComponentView.js`. Tools like [Bundlephobia](https://bundlephobia.com/result?p=tiptap) throw an error over this.

**Comment by philippkuehn** [comment]
You are absolutely right! This is fixed in the current version of `tiptap` and `tiptap-extensions`!
