### ISSUE TITLE
Add support for images

### ISSUE THREAD

**Issue by philippkuehn** [heyscrumpy/tiptap#5]
Where should I put all my gifs?!? We'll need basic image support.

**Comment by philippkuehn** [comment]
There is now a [basic example for images](https://tiptap.scrumpy.io/#/images).
You can also create your own image extension with upload support or something else. For a quick start you can extend [the default image extension](https://github.com/heyscrumpy/tiptap/blob/master/packages/tiptap-extensions/src/nodes/Image.js).

**Comment by philippkuehn** [comment]
@PhouvanhKCSV Feel free to create you own extension! https://github.com/heyscrumpy/tiptap/issues/5#issuecomment-417781070

**Comment by bswank** [comment]
@philippkuehn Did you end up creating an extension. Looking to do the same and wondering how it went for you.
