### ISSUE TITLE
Insert newline functionality broken since v0.16.0

### ISSUE THREAD

**Issue by nodegin** [heyscrumpy/tiptap#53]
After v0.16.0, I cannot insert new line at the line end by pressing enter key.

If pressing enter key at the middle of the line, the line break still able to insert.

I tested v0.15.0 line breaks can still be inserted in this version.

**Comment by philippkuehn** [comment]
I can't see this behavior at the examples page. Can you tell me your browser and provide an example on codesandbox?

**Comment by nodegin** [comment]
I am using chrome 68.0.3440.106, I can reproduce it in my local project, but it works well after duplicating to codesandbox, I tried `rm -rf node_modules` with fresh install but still facing the same problem... Any clue how to debug the issue?

**Comment by nodegin** [comment]
It turns out to be a Nuxt problem, looks fixed by removing `node_modules` and `.nuxt` directories. Thanks.

**Comment by nodegin** [comment]
The problem persists after deploying to production server...

**Comment by nodegin** [comment]
Damn, I fixed by removing package-lock.json, seems something went wrong with NPM

**Comment by lbjones** [comment]
FYI I also saw this issue after upgrading from v0.19 to v1.7.0.  Had to rm node_modules and yarn cache clean to fix this issue.

**Comment by zmts** [comment]
This problem related with ProseMirror
https://github.com/ProseMirror/prosemirror/issues/664

**Comment by AbidKhairyAK** [comment]
manual fix for this issue 
https://github.com/scrumpy/tiptap/issues/426#issuecomment-528995046
