### ISSUE TITLE
Something missing in Blockquote Implementation?

### ISSUE THREAD

**Issue by manogi** [heyscrumpy/tiptap#56]
Hey there, 

thanks for this great package. I am right now building a Laravel Nova package for adding your text editor, which comes along nicely.

I have a problem implementing the blockquote node, though - do you have an example implementation?

It seems (it looks this way in the Prosemirror example) there should be a button to decrement the blockquote level. Have you already worked on that and I haven't found it yet?

Thanks again,
Sebastian

**Comment by philippkuehn** [comment]
Hey, I added a blockquote button to the [basic demo](https://tiptap.scrumpy.io/).

But there was a bug when toggling blockquotes. This is fixed in the current version.

**Comment by manogi** [comment]
Great - I will add the blockquote button to the Laravel Nova package today, then!
