### ISSUE TITLE
Demo website is not working

### ISSUE THREAD

**Issue by girardinsamuel** [heyscrumpy/tiptap#6]
The browser return SSL_ERROR_RX_RECORD_TOO_LONG when accessing the website https://tiptap.scrumpy.io !

It is happening on Firefox.

Thanks

**Comment by philippkuehn** [comment]
Hey, which plattform and version do you use?

For me it's looking fine.

![5w4xif5abm](https://user-images.githubusercontent.com/2500670/44705596-5f49e380-aa9f-11e8-92a4-14314bbc5a4a.png)

**Comment by hanspagel** [comment]
SSL configuration looks good. E. g. A+ on Quality Labs.

**Comment by girardinsamuel** [comment]
Hello !

Right now I have tested it at work on Windows 7 and firefox 61.0.2 (same as you), but it might be due to our network rules. Because it's indeed working on my phone.

On Internet Explorer the browser throw an error: 
> This page can’t be displayed: Turn on TLS 1.0, TLS 1.1 and TLS 1.2 in Advanced Settings

**Comment by girardinsamuel** [comment]
Yeah I guess it's a problem on my side.

Thank you for the quick help.
