### ISSUE TITLE
Medium-style "Add" button

### ISSUE THREAD

**Issue by themsaid** [heyscrumpy/tiptap#61]
I'd like to be able to detect if cursor is on an empty line and show a menu where people can use to Add (image, video, iframe, etc...)

Can you help me figure out how to achieve that? I tried to add a plugin but the `view()` method is never called:

```
export default function () {
	return new Plugin({
		view(editorView) {
			return new AddNodes({ editorView })
		},
	})
}
```

**Comment by philippkuehn** [comment]
Hey @themsaid!

You have to create an extension for that. Within an extension you are able to pass prosemirror plugins. So you can try that:

```js
import { Extension, Plugin } from 'tiptap'

export default class CustomExtension extends Extension {

	get name() {
		return 'custom'
	}

	get plugins() {
		return [
			new Plugin({
				view(editorView) {
					// your code
				},
			}),
		]
	}

}
```

Building a medium like editor is definitely one of the things I would love to see on the example page. But I'm not sure what is the best way to achieve this at the moment. Maybe that will be easier in v1.0 (#41) after replacing scoped slots with components.

For now, it may help how I built the bubble menu. You can see it here:
https://github.com/heyscrumpy/tiptap/blob/master/packages/tiptap/src/utils/menuBubble.js

**Comment by philippkuehn** [comment]
I'll try my best ✌️

**Comment by philippkuehn** [comment]
Hey, I added a new `floatingMenu` slot in the latest version. There is also [a basic example](http://localhost:3000/floating-menu) for it. Hope it helps!

**Comment by farshidgh70** [comment]
Hi. How can i add another extension to floatingMenu (ex: button, video, etc...)
