### ISSUE TITLE
Problems with menububble

### ISSUE THREAD

**Issue by fmay** [heyscrumpy/tiptap#71]
Hi - I am an intermediate coder at best but am pretty competent with vue. 

I have been trying to implement a medium style editor but when I use menububble (using your own example [here](https://github.com/heyscrumpy/tiptap/blob/master/examples/Components/Routes/MenuBubble/index.vue)) in a test page in my project, the menu renders above the editor, not in it.

If you can manage another question, I am using vuetify and could not figure out how to implement a vuetify driven menu bar that is outside the editor component so it can stay fixed while the content below it scrolls. Are there any examples of something similar?

Thanks!!

**Comment by fmay** [comment]
I sorted it out now. The viewport coordinates were ok but I have to set positioning: absolute myself. I think the strength of tiptap is that the developer has total visual control but it takes a little getting used to,

**Comment by philippkuehn** [comment]
hey @fmay, you are absolutely right! this is something that will be better in v1.0!

**Comment by fmay** [comment]
Übrigens - ich mag sehr was Du mit Workeer machst. Wie läuft's? Es braucht mehr solche Initiativen, vor allem hier in England. Das Niveau einer Zivilisation wurde daran gemessen, wie die Gefangenen behandelt wurden. Heutzutage könnte man es daran messen, wie man Flüchtlinge behandelt.

**Comment by iliyaZelenko** [comment]
I tried to make a bubble with vuetify `<v-tooltip>`.
I had a problem that the tiptap returns a position from the bottom of the page (`menu.bottom`, not absolutely), and vuetify accepted the coordinates by and as the absolute value of the top.

The following code worked for me:

```vue
<v-tooltip
  :value="menu.isActive"
  :position-x="menu.left"
  :position-y="getMenuY(menu)"
  absolute
  top
>
```
```js
getMenuY (menu) {
  // the height of the whole page - the height of the window - how much the page is scrolled from the top
  const diff = document.documentElement.scrollHeight - window.innerHeight - window.scrollY
  // bottom position relative to the bottom of the window
  const bottomRelatedToWindow = menu.bottom - diff

  // top position
  return window.innerHeight - bottomRelatedToWindow
}
```

I use tiptap tiptap `1.14.0`.

Hope this helps someone.

**Comment by kushtra24** [comment]
for me it was just a css issue I just added this to my css styles


```
.menububble.is-active {
    opacity: 1;
    visibility: visible;
}

.menububble {
    position: absolute;
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex;
    z-index: 20;
    background: #000;
    border-radius: 5px;
    padding: .3rem;
    margin-bottom: .5rem;
    -webkit-transform: translateX(-50%);
    transform: translateX(-50%);
    visibility: hidden;
    opacity: 0;
    -webkit-transition: opacity .2s,visibility .2s;
    transition: opacity .2s,visibility .2s;
    i {
        color: white;
        padding: 5px;
        &:hover {
            cursor: pointer;
            background-color: #CCCCCC;
        }
    }
}
```
Note: I used font-awesome for icons like this:

```
<editor-menu-bubble :editor="editor"
 :keep-in-bounds="keepInBounds" 
v-slot="{ commands, isActive, menu }">
<div class="menububble" 
:class="{ 'is-active': menu.isActive }"
 :style="`left: ${menu.left}px; bottom: ${menu.bottom}px;`">

// here I used a Font awesome icon insted text
<i class="fas fa-bold menububble__button" 
:class="{ 'is-active': isActive.bold() }" 
@click="commands.bold"></i>

...
```
