### ISSUE TITLE
How to set link attributes

### ISSUE THREAD

**Issue by fmay** [heyscrumpy/tiptap#72]
Using your example for link insertion ...

```
    setLinkUrl(url, type, focus) {
      type.command({ href: url, rel: '', target: '__blank', class:'my-class' })
      this.hideLinkMenu()
      focus()
    }
```

What is the correct approach for managing attributes such as target, class, rel etc?

Thanks

**Comment by fmay** [comment]
Sorry for answering my own questions!! I got off my ass and looked at the source and see how the nodes/marks are created and so it seems clear I should just write my own nodes and marks, which was next on my list anyway.

The more I see, the more I like.

**Comment by antimodern** [comment]
@fmay hello

> I should just write my own nodes and marks

Can you please explain in two words what did you mean? Also want `target="_blank"` for the links...

**Comment by Ken-vdE** [comment]
> Sorry for answering my own questions!! I got off my ass and looked at the source and see how the nodes/marks are created and so it seems clear I should just write my own nodes and marks, which was next on my list anyway.
> 
> The more I see, the more I like.

@fmay Could you show us a code example? I want to do something like this: 
```
this.editor.chain().focus().extendMarkRange('link').setLink({href: url, class: 'some-class'}).run()
```
However the class attribute can not be added dynamically like this unfortunately...
