### ISSUE TITLE
A focus event when clicking the content div

### ISSUE THREAD

**Issue by PsidomPC** [heyscrumpy/tiptap#73]
Hey really appreciate the nice work - 

I am wondering if there is a method to emit a focus event when clicking the div (slot="content")? Especially if the content div has a min height. Something like how the editor here (I mean github) works. Currently when I click the div with a min height of 200px, it won't focus unless I happen to click at the top of the div and also it only focuses on the first line. I wonder if there's already a feature built in that I am not aware of or this fits as a feature request. Thanks in advance!

**Comment by philippkuehn** [comment]
Hey @PsidomPC. Inside the content slot there is another `div` with the class `ProseMirror`. You have to put your styling on this element. Unfortunately I didn't found a way to prevent that nesting for now.

**Comment by PsidomPC** [comment]
@philippkuehn Awesome. That trick worked for me. Many thanks!
