### ISSUE TITLE
Selected image

### ISSUE THREAD

**Issue by fmay** [heyscrumpy/tiptap#79]
I've been poring over how to select/activate an image for quite a while. None of your examples quite cover my use case.

I have inserted an img happily in the page. I need to be able to click on the image and get the image's attributes so I can then load my own dialog. 

I currently have a floating menu that does appear when I click on the image but the image does not appear to be active/selected.

Any ideas gratefully received.

**Comment by philippkuehn** [comment]
I think that should be possible with a node view so you can render your image as a vue component.

**Comment by bswank** [comment]
@fmay Did you ever get this working in a way you're happy with?

**Comment by pymarco** [comment]
I too am stuck trying to figure this one out.
