### ISSUE TITLE
Extend example in doc

### ISSUE THREAD

**Issue by paultru** [heyscrumpy/tiptap#8]
Hi there. Great job already! Thank you guys.

Would really love to see an example of how to pass a prop to a custom extension. 
for example i copied your `TodoItem`-extension and tried to pass an object in like this:

```
<ul data-type="todo_list">
    <li 
        :custom-prop="customProp"
        data-type="todo_item" 
        data-done="true">
         Buy beer
    </li>
</ul>
```

and then tried to use this custom-prop inside of the template logic of `TodoItem`, but it wasn't available there.
is there a way to achive something like this? an example-code for this in the doc would help not only me, but also other.

**Comment by philippkuehn** [comment]
Hey, thanks for your feedback! Can you tell me what you want to do with custom props? At the moment all data should be saved as node attributes (see todo item extension). All these attrs are available in your vue component.

Maybe you could paste your full extension here?

**Comment by paultru** [comment]
oh yes that actually helped me a lot, thank you. now i have access to the passed variables, awesome! But i'm still a bit confused about the reactivity you've mentioned through vuex. How would i get access to the store inside this custom vue-view? Do i have to pass the whole store as a prop?

**Comment by philippkuehn** [comment]
Did you ever worked with Vuex? Maybe you should take a look, it's an amazing plugin. The good thing is that you don't have to pass everything as a props because there is a global store. For example you can import `customValue` directly from your store.

```js
import { mapGetters } from 'vuex'

export default class TodoItemNode extends Node {

  ...

  get view() {
    return {
      props: ['node', 'updateAttrs', 'editable'],
      computed: {
        ...mapGetters([
          'customValue',
        ])
      },
      methods: {
        onChange() {
          this.updateAttrs({
            done: !this.node.attrs.done,
          })
        },
      },
      template: `
        <li data-type="todo_item" :data-done="node.attrs.done.toString()">
          <span class="todo-checkbox" contenteditable="false" @click="onChange"></span>
          <div class="todo-content" ref="content" :contenteditable="editable.toString()"></div>
          <div>
            {{ customValue }}
          </div>
        </li>
      `,
    }
  }

}
```

**Comment by paultru** [comment]
yes i use it every time, when im playing around with vue. thank you for your quick and helpful answers 🤙

**Comment by rameezcubet** [comment]
It seems tiptap doesnt have an option like v-model="" so what if i want to attach a vuex store getter computed valute value to tiptap?

**Comment by laurensiusadi** [comment]
@rameezcubet 
You can bind v-model to a computed with get() and set() like this
```
computed: {
  customValue: { 
    get() {
      return this.$store.getters.customValue
    },
    set(customValue){
      this.$store.commit('setCustomValue', customValue)
    }
  }
},
```
