### ISSUE TITLE
Single File vue Component example

### ISSUE THREAD

**Issue by panayotisk** [heyscrumpy/tiptap#81]
Is it possible to have an example of using our ready SFCs when creating out extensions? I saw the Iframe sample and I was wondering how to do something like it using an SFC.

**Comment by philippkuehn** [comment]
Hey @panayotisk! You can already do that.

```js
import { Node } from 'tiptap'
import CustomComponent from './CustomComponent.vue'

export default class CustomNode extends Node {

	get name() {
		return 'custom_node'
	}

	get view() {
		return CustomComponent
	}

}
```

**Comment by panayotisk** [comment]
@philippkuehn is there also a way to set the SFC component's parent? I need to access the vuex store and it would also be helpful to see its properties in chrome dev tools as is suggested here: https://github.com/buefy/buefy/issues/55#issuecomment-343859081
Or should I use a different approach?

**Comment by philippkuehn** [comment]
A good point. Didn't know that!

**Comment by philippkuehn** [comment]
I added this `parent` option in `tiptap@0.20.0`. Thanks for the hint!

**Comment by panayotisk** [comment]
Great! Thank you for that.
