### ISSUE TITLE
Create Vue components on stored text

### ISSUE THREAD

**Issue by panayotisk** [heyscrumpy/tiptap#82]
Using a custom mention extension as a Vue component I was wondering how to re-create vue components from stored html text. When the editor is mounted I need to show the text it had when the user left it, so all mention components should be recreated. 
Following the Mention.js example I tried something like this in mounted():
`this.insertMention({
			range,
			attrs
		});` 
but I realized insertMention() is initialized with command() at the first call to onEnter(). 
Is there some recommended way of re-creating the vue components? This should normally apply not only to mentions but to anything is created as vue component in the editor.

**Comment by philippkuehn** [comment]
I'm not sure what you mean. Your mentions from your stored HTML are created as long as your schema (parseDOM) is set up correctly. You don't have to call any functions on mounted. Can you provide a repo or sandbox of your problem?

**Comment by panayotisk** [comment]
Yes, you are right, I was not aware of that! They were not shown because I had an error in the css selector in parseDom() function in get schema()... Thank you!
