### ISSUE TITLE
Detect editor blur?

### ISSUE THREAD

**Issue by Zanzavar** [heyscrumpy/tiptap#83]
What would be the optimal way to detect the editor blur event? I tried adding @blur on the editor containing div but it does not seem to work.

 Would it make sense to expose an event handler (e.g. @blur) on the editor?

**Comment by saloustrosm** [comment]
@Zanzavar for now you could use @init event of the editor componenet it will return an event where if you call a function with it like 
`inited(event) {
            event.view.dom.addEventListener('blur', function() {
                theEditorIsBlured=doSomething
            });
        },`
you are able to catch the blur event.

**Comment by philippkuehn** [comment]
This will be a `focus` and `blur` event in v1.0.

**Comment by philippkuehn** [comment]
v1.0 is released.

**Comment by panayotisk** [comment]
@philippkuehn , is it possible to also pass the blur event data along with state and view in the Editor.js? For instance I need to access the relatedTarget property from the blur handler. Something like the following:
```
view.dom.addEventListener('blur', (event) => this.options.onBlur({
      state: this.state,
      view: this.view,
      originalEvent: event
    }))
```
The same for the focus event.
Thank you!

**Comment by philippkuehn** [comment]
@panayotisk You are right! Will fix this in the next release!

**Comment by philippkuehn** [comment]
@panayotisk The event is added in the latest version

**Comment by silvaDominic** [comment]
Is there anyway to obtain the actual editor instance using blur/focus events? My use case has multiple editors on a page and I would like to obtain the editor itself to operate on. Currently I have to set a data-prop with the name or index on the editor and then pick it off the event to use for referencing the actual editor.

**Comment by panayotisk** [comment]
I am using the editor in a vue SFC and I keep a data property in it that holds the created instance.
```
data() {
 return {
   editor: new Editor({...})
 }
}
```

**Comment by silvaDominic** [comment]
@panayotisk Right, I have the same thing, but as I said, my use case has _many_ editors stored as an array.

These are initialized like:
`      this.answers.forEach(answer => {
        this.editors.push(new TextEditor(this.createEditor(answer)));
      });`
      
Where createEditor returns an instantiated Editor. On blur I want to perform some logic that I cannot do with the event object.
