### ISSUE TITLE
Custom Schema for Editor initialisation

### ISSUE THREAD

**Issue by ChrisWagemakers** [heyscrumpy/tiptap#85]
Would be awesome if it’s possible to pass a custom Schema to the initialisation of the editor view.

Example use case; I want to initialise an instance of the editor where it’s only possible to have **one** Paragraph. 

Maybe this is already possible then I would love to learn how.
Fantastic editor!

**Comment by PierBover** [comment]
Prosemirror allows this.

https://prosemirror.net/docs/guide/#schema

Does Tiptap allows passing initialization options to Prosemirror?

**Comment by ChrisWagemakers** [comment]
Solution could be as simple as removing builtInNodes, and add them to tiptap-extensions. 
This way users can pick if they use the Doc node from tiptap-exentions or their own variation. Another option would be to include a different merge strategy in ExtensionManager.

**Comment by ChrisWagemakers** [comment]
@philippkuehn I agree with you. Adding the option {useBuildInNodes: false} seems like a great idea to me!

**Comment by philippkuehn** [comment]
I've added a `useBuiltInExtensions` option in v1.1 👍
