### ISSUE TITLE
Disable (or filter) drag and drop

### ISSUE THREAD

**Issue by panayotisk** [heyscrumpy/tiptap#87]
Is there a straightforward way to disable drag and drop on the editor, or somehow filter what is allowed to be dropped from external source (I mean something not already in the editor)? I do not want the editor to accept some custom drop items I have, only the parent component should be able to accept them.

Thank you

**Comment by philippkuehn** [comment]
Hey @panayotisk, you can try to add an extension with a prosemirror plugin that prevents some events (e.g. drop). You can read more in the [prosemirror docs](https://prosemirror.net/docs/ref/#view.EditorProps).

```js
import { Extension, Plugin } from 'tiptap'

export default class EventHandler extends Extension {

  get name() {
    return 'event_handler'
  }

  get plugins() {
    return [
      new Plugin({
        props: {
          handleDOMEvents: {
            drop(view, event) {
              // some condition
              return
            },
          },
        },
      }),
    ]
  }

}
```
