### ISSUE TITLE
Auto link feature implementation

### ISSUE THREAD

**Issue by zmts** [heyscrumpy/tiptap#88]
Hi here!

I have very common case. 
1) user pasted link _or type_ as text
2) user press space or enter button
3) pasted url should transform into `<a href="pasted_link">pasted_link</a>`

There is code...
```
import { Mark } from 'tiptap'
import { markInputRule } from 'tiptap-commands'

export default class AutoLinkMark extends Mark {
  get name () {
    return 'auto-link'
  }

  get schema () {
    return {
      attrs: {
        href: {
          default: null
        }
      },
      parseDOM: [
        {
          tag: 'a[href]',
          getAttrs: dom => ({
            href: dom.getAttribute('href')
          })
        }
      ],
      toDOM: node => [
        'a',
        { href: 'pasted_url' }, // how make it ?
        0
      ]
    }
  }

  inputRules ({ type }) {
    return [
      markInputRule(/((((http|https):\/\/)|(www\.))[^\s]+)\s$/g, type)
    ]
  }
}
```
As result this code wrap pasted code as `<a>pasted_link</a>`
But I don't  imagine how to insert pasted url into `href` prop.

Hope somebody have some thoughts about it.

**Comment by zmts** [comment]
Yes, as pasted text nothing isn't fires. All fine work after user paste  some link **and then press space key**, then pasted text successfully trigger inputRules. But anyway I can't handle fired content.

@philippkuehn or maybe you have some alternative approach to implement **auto link feature** ?

**Comment by philippkuehn** [comment]
You could try to add a plugin for this. There is a [transformPasted](https://discuss.prosemirror.net/t/bug-while-transforming-slices-or-maybe-just-doing-things-wrong/669) event, where you have access to pasted text.

**Comment by zmts** [comment]
I hear about it but how use it with tiptap ?

**Comment by philippkuehn** [comment]
You can create a custom extension with a prosemirror plugins like this:

```js
import { Extension, Plugin } from 'tiptap'

export default class CustomExtension extends Extension {

  get name() {
    return 'custom_extension'
  }

  get plugins() {
    return [
      new Plugin({
        props: {
          transformPasted() => {
            // handle pasted links
          },
        },
      }),
    ]
  }

}
```

**Comment by zmts** [comment]
tnx!

**Comment by christophermiles** [comment]
Hi @zmts, are you able to share any progress with this? Looking to implement this functionality and would be interested to see how you've gone with it. I'm just getting my head around tiptap (the Suggestions plugin is great).

**Comment by zmts** [comment]
@christophermiles currently I paused this feature and use native link node. Anyway when I found good solution I will commit to this thread.

**Comment by philippkuehn** [comment]
I found a way to get this working. Coming in the next release. 👍

**Comment by philippkuehn** [comment]
You can use `pasteRules` in tiptap v1.3.0. 🎉

This paste rule is defined for links now:

```js
import { Mark } from 'tiptap'
import { pasteRule } from 'tiptap-commands'

export default class Link extends Mark {

  pasteRules({ type }) {
    return [
      pasteRule(
        /https?:\/\/(www\.)?[-a-zA-Z0-9@:%._+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_+.~#?&//=]*)/g,
        type,
        url => ({ href: url }),
      ),
    ]
  }

}
```

**Comment by roybekhuis** [comment]
@philippkuehn, thank you for implementing this. I don't quite understand how to use the pasteRules though, could you provide an example?

**Comment by roybekhuis** [comment]
@zmts thanks, somehow I missed that...

**Comment by MrBuggy** [comment]
Hi,
I managed to implement the `pasteRules` and it works. Now I'm struggling with implementing the `inputRules`. So I would like to define a `regex` and force a auto-link, when during typing the typed string is matching the regex.

This is what I tried so far:
```
  // eslint-disable-next-line
  inputRules({ type }) {
    return [
      markInputRule(
        /https?:\/\/(www\.)?[-a-zA-Z0-9@:%._+~#=]{2,256}\.[a-zA-Z]{2,}\b([-a-zA-Z0-9@:%_+.~#?&//=]*)(\s|\n)/g,
        type,
        (url) => ({ href: url }),
      ),
    ];
  }
```
At the moment, when I type in `https://www.google` it forces an auto-link. But when I add `.com` at the end, it changes the link text to `www` instead of `https://www.google.com`. When inspecting the rendered element in the dev tools, the `href` has this value `https://www.google.com.www`. I don't know how to fix this. Any ideas?

I took the schema etc. from here: https://github.com/heyscrumpy/tiptap/blob/master/packages/tiptap-extensions/src/marks/Link.js

**Comment by rdlh** [comment]
Hi @MrBuggy 

I've found a way to enable auto-linking with this code: 

`link.js`
```js
  inputRules({ type }) {
    return [
      linkInputRule(/https?:\/\/(www\.)?[-a-zA-Z0-9@:%._+~#=]{2,256}\.[a-zA-Z]{2,}\b([-a-zA-Z0-9@:%_+.~#?&//=]*)(\s|\n)$/g,
        type,
        (url) => ({ href: url }),
      ),
    ]
  }
```

`linkInputRule.js`
```js
import { InputRule } from 'prosemirror-inputrules'

export default function (regexp, markType, getAttrs) {
  return new InputRule(regexp, (state, match, start, end) => {

    // really crappy, but working.
    match.splice(1, 3)
    match[0] = match[0].trim()

    const attrs = getAttrs instanceof Function ? getAttrs(match) : getAttrs
    const { tr } = state
    let markEnd = end
    let markStart = start

    tr.addMark(markStart, markEnd, markType.create(attrs))
    tr.removeStoredMark(markType)
    return tr
  })
}

```

## Known issue:

You've got to double-press the <SPACE> key, first press will trigger Mark creation, second one will add a "real" space. 
I'm currently trying to find a way to prevent `inputRules.handleTextInput` to cancel the input or to dispatch the Transaction in`linkInputRule.InputRule` 
Some info [here](https://github.com/ProseMirror/prosemirror-inputrules/blob/master/src/inputrules.js#L91) and here

**Comment by Amfishers** [comment]
Hi @rdlh 
are you able to share any progress with this?
>You've got to double-press the key, first press will trigger Mark creation, second one will add a "real" space.
I'm currently trying to find a way to prevent inputRules.handleTextInput to cancel the input or to dispatch the Transaction inlinkInputRule.InputRule
Some info here and here

**Comment by rdlh** [comment]
Hi @Amfishers, we haven't found any "good" way to prevent this.
Looks like our users are used to double tap space bar now haha.

**Comment by DebaPrasad14** [comment]
Hi @rdlh @philippkuehn, I am trying to implement CustomLink extension without changing your code where I am adding a feature taget="_blank" as well as auto-linking. but I m getting error while writing input rules for auto linking as above mentioned by @rdlh.
