### ISSUE TITLE
Building and running locally

### ISSUE THREAD

**Issue by pdiveris** [heyscrumpy/tiptap#9]
Hi

I've checkout the current code base and I am running 

`npm install` and `npm start`

However, I am getting a series of errors like this:

`ERROR in ./packages/tiptap-commands/src/index.js
Module not found: Error: Can't resolve 'prosemirror-commands' in '/Users/pedro/Projects/tiptap-master/packages/tiptap-commands/src'
 @ ./packages/tiptap-commands/src/index.js 1:0-369 9:0-13:69 9:0-13:69 9:0-13:69 9:0-13:69 9:0-13:69 9:0-13:69 9:0-13:69 9:0-13:69 9:0`

What's the correct way of building and running locally?

Thank you

**Comment by hanspagel** [comment]
Hey @pdiveris! Which node version are you using?

**Comment by pdiveris** [comment]
`node v6.11.5 `
and
`npm 6.4.1`

**Comment by philippkuehn** [comment]
Hey, there is a problem for npm users at the moment. I‘ve used yarn for local development with a feature called workspaces. At the moment there is no equivalent for npm.

So you can do yarn install and yarn start.

**Comment by pdiveris** [comment]
OK, will give it a go, thanks. It's about time I delve into yarn anyway..

**Comment by hanspagel** [comment]
I think you'll need node support for imports anyway (with yarn or npm), whichs comes with 8 or 9, not sure. Seems like it's running on my machine with Node v10 and npm.

**Comment by pdiveris** [comment]
I can confirm that this works with yarn and node 10.x so I'll close this issue.

**Comment by hanspagel** [comment]
Nice! Thanks, @pdiveris!
